version: "3.7"

name: servicell-api

services:
  db:
    image: mysql:8.0.36
    container_name: servicell-mysql-db
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: servicell
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 3
    security_opt:
      - seccomp:unconfined

volumes:
  mysql-data:
    driver: local
